# Generated by Django 3.1.7 on 2021-03-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(null=True)),
                ('weight', models.IntegerField(null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=150)),
                ('age', models.PositiveIntegerField()),
                ('activityLevel', models.CharField(choices=[('Sedentary', 'Sedentary'), ('LightlyActive', 'LightlyActive'), ('Active', 'Active'), ('HighlyActive', 'HighlyActive')], max_length=150)),
            ],
        ),
    ]
